services:
  rlbook:
    image: quay.io/jupyter/datascience-notebook
    volumes:
      - .:/home/jovyan
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    working_dir: /home/jovyan
    command: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token="${JUPYTER_TOKEN}" --NotebookApp.password='' --notebook-dir=/home/jovyan
